#!/usr/bin/env node

import fs from 'fs';
import path from 'path';

/**
 * Injects the Webflow HTML content into the Next.js page.tsx
 * Handles path conversions and proper JSX escaping
 */

async function injectHTML() {
  try {
    console.log('[v0] Starting HTML injection process...');

    // Read index.html
    const indexPath = 'index.html';
    let htmlContent = fs.readFileSync(indexPath, 'utf-8');

    console.log('[v0] Read index.html successfully');

    // Extract body content
    const bodyMatch = htmlContent.match(/<body[^>]*>([\s\S]*?)<\/body>/);
    if (!bodyMatch) {
      throw new Error('Could not extract body content from index.html');
    }

    let bodyContent = bodyMatch[1];

    console.log('[v0] Extracted body content');

    // Basic HTML to JSX conversions
    // 1. Convert class= to className=
    bodyContent = bodyContent.replace(/\bclass="/g, 'className="');

    // 2. Convert for= to htmlFor=
    bodyContent = bodyContent.replace(/\bfor="/g, 'htmlFor="');

    // 3. Fix self-closing tags
    bodyContent = bodyContent
      .replace(/<img([^>]*)>/g, '<img$1 />')
      .replace(/<br>/g, '<br />')
      .replace(/<input([^>]*)>/g, '<input$1 />')
      .replace(/<hr>/g, '<hr />')
      .replace(/<meta([^>]*)>/g, '<meta$1 />')
      .replace(/<link([^>]*)>/g, '<link$1 />');

    // 4. Fix image paths (./images/ → /images/)
    bodyContent = bodyContent
      .replace(/src="\.\//g, 'src="/')
      .replace(/href="\.\//g, 'href="/')
      .replace(/srcset="\.\//g, 'srcset="/')
      .replace(/data-src="\.\//g, 'data-src="/');

    // 5. Escape special characters for proper JSX
    // Escape backticks and template literals
    bodyContent = bodyContent
      .replace(/`/g, '\\`')
      .replace(/\$/g, '\\$');

    console.log('[v0] Converted HTML to JSX syntax');

    // Create the page content with the HTML injected
    const pageContent = `'use client'

/**
 * Home page - Webflow HTML export converted to Next.js
 * Auto-generated by inject-html.js
 * All Webflow HTML structure, classes, and data attributes are preserved.
 */

import { useEffect } from 'react'

export default function Home() {
  useEffect(() => {
    // Initialize Webflow interactions after DOM loads
    const initWebflow = async () => {
      try {
        // Load GSAP animations
        const gsapScript = document.createElement('script')
        gsapScript.src = '/scripts/gsap.min.js'
        document.body.appendChild(gsapScript)

        // Load DrawSVGPlugin for SVG animations
        const drawScript = document.createElement('script')
        drawScript.src = '/scripts/DrawSVGPlugin.min.js'
        document.body.appendChild(drawScript)

        // Load ScrollTrigger for scroll-based animations
        const scrollScript = document.createElement('script')
        scrollScript.src = '/scripts/ScrollTrigger.min.js'
        document.body.appendChild(scrollScript)

        // Load SplitText for text animations
        const splitScript = document.createElement('script')
        splitScript.src = '/scripts/SplitText.min.js'
        document.body.appendChild(splitScript)

        // Load Lenis for smooth scrolling
        const lenisScript = document.createElement('script')
        lenisScript.src = '/scripts/lenis.min.js'
        lenisScript.async = true
        document.body.appendChild(lenisScript)

        // Load Swiper for carousels
        const swiperScript = document.createElement('script')
        swiperScript.src = '/scripts/swiper-bundle.min.js'
        document.body.appendChild(swiperScript)

        // Load mouse follower
        const mouseScript = document.createElement('script')
        mouseScript.src = '/scripts/mouse-follower.min.js'
        document.body.appendChild(mouseScript)

        // Load main Webflow script for all interactions
        const webflowScript = document.createElement('script')
        webflowScript.src = '/scripts/webflow.8df354fb.c0169e213cfb0728.js'
        webflowScript.async = true
        document.body.appendChild(webflowScript)

        // Load main-world for custom animations
        const mainScript = document.createElement('script')
        mainScript.src = '/scripts/main-world.ts-B-snRbqi.js'
        mainScript.type = 'module'
        mainScript.async = true
        document.body.appendChild(mainScript)
      } catch (error) {
        console.error('[v0] Error initializing Webflow scripts:', error)
      }
    }

    initWebflow()
  }, [])

  return (
    <>
      <div dangerouslySetInnerHTML={{
        __html: \`${bodyContent}\`
      }} />
    </>
  )
}
`;

    // Write to page.tsx
    fs.writeFileSync('src/app/page.tsx', pageContent, 'utf-8');

    console.log('[v0] ✓ Successfully injected HTML into src/app/page.tsx');
    console.log(`[v0] Generated page size: ${pageContent.length} bytes`);

    return true;
  } catch (error) {
    console.error('[v0] Error during HTML injection:', error.message);
    return false;
  }
}

// Run the injection
injectHTML().then((success) => {
  if (!success) {
    process.exit(1);
  }
});
